### ISSUE TITLE
There was an error executing the modifyGuildMember command: Client error

### ISSUE THREAD

**Issue by ghost** [restcord/restcord#83]
Hello,

We've suddenly been hit with the below error;
```
    There was an error executing the modifyGuildMember command: Client error: `PATCH https://discordapp.com/api/v6/guilds/1111/members/1111` resulted in a `400 BAD REQUEST` response:\n
```

Never happened before, any ideas?

**Comment by Crypta-Eve** [comment]
https://i.imgur.com/FbKyY3u.png

**Comment by Crypta-Eve** [comment]
Temporary patch

https://gist.github.com/Crypta-Eve/2aa4b36585e4bc73f6fa03028e6b3b2d

**Comment by Crypta-Eve** [comment]
I have submitted PR #84 in order to fix this in the library for now. Whilst it will be overwritten by the service description generator. That is currently non functional anyway.

**Comment by dstevens79** [comment]
if you are a nub at this and want to fix this the easy way 👍 
sudo nano /var/www/seat/vendor/restcord/restcord/src/Resources/service_description-v6.json 
delete lines 459 & 468
this worked for me on 6-30-19

**Comment by warlof** [comment]
A fix is available on dev branch 😜
@aequasi when would it be tagged? 😕

**Comment by sky-lake** [comment]
Still an issue with 0.3.2.  Please apply this fix @aequasi (or sort out an equivalent solution).  Without it, `guild->modifyGuildMember()` is unusable unless the target happens to be in the voice channel.

> mute | boolean | whether the user is muted in voice channels. Will throw a 400 if the user is not in a voice channel
([API Doc](https://discordapp.com/developers/docs/resources/guild#modify-guild-member))

**Comment by aequasi** [comment]
Have you tried dev-develop?

**Comment by zerathun** [comment]
This Error persists with me.. is there a workaround or did i miss something? .. i also updated withhe composer on dev-develop / dev-master didnt change a thing. TY

**Comment by cryptiklemur** [comment]
If this error is still happening, please open a new issue
