### ISSUE TITLE
GuildMember join_at type

### ISSUE THREAD

**Issue by joobi** [restcord/restcord#89]
The join_at of the GuildMember is set to int.
It should be set as string since it is a date.
Setting to int force into giving only the year.

**Comment by OliverSchloebe** [comment]
Just noticed that too after I updated the package yesterday.

**Comment by BlitzofEmpire** [comment]
Anyway to solve this? because having just the year isn't really useful, tried to understand & fix it but i dont know how.. :(

**Comment by Xbirdfr** [comment]
Hi ! this issue is still relevant, is someone have a fix until rescord will be fix ?

**Comment by LeigerGaming** [comment]
It looks like this has been fixed already, by @aequasi in #102 (on Oct 14, 2019) which changed the type from `int` to `\DateTimeImmutable`.

**Comment by cryptiklemur** [comment]
The original DTO type was fixed in PR #102. RestCord 0.9.0 also removed DTO coercion, so joined_at and other Discord timestamps remain the strings returned by the API.
